### PR TITLE
Integrate ActionBarSherlock

### PR DESCRIPTION
**Pull request by ashokgelal**
Finally I was able to integrate ActionBarSherlock after spending extended hours. Hopefully, this push will save others from spending their precious hours trying to get ABS working.

### CODE REVIEW

**Comment by ashokgelal** [comment]
<del>There is a small caveat with this that I just discovered. <code> mvn clean install </code> works but running it from intelliJ or eclipse gives an error - 
<code>
java: ~/CleanAndroidCode/cleanandroidcode/src/main/java/info/piwai/cleanandroidcode/HelloApplication.java:15: cannot find symbol
symbol  : class EntryPointsModule
location: class info.piwai.cleanandroidcode.HelloApplication
</code></del>

<del>Not sure why it cannot find <code>EntryPointsModule</code>. I might be overlooking something.</del>

EDIT: Never mind. I was doing something silly with the run configuration. Instead of creating Maven run configs, I was creating regular configs.

**Comment by pyricau** [comment]
The diff on Maven files is way to big, due to a different indentation formatting. Could you please reformat it, so that I get a chance to understand what you really changed.

If I understand correctly, this also changes the steps to get a working project. Could you please also update the README.md to reflect that ?

**Comment by ashokgelal** [comment]
There are really not many changes - I only added few lines of code. 

No, it doesn't change the steps. I will send another pull request.

**Comment by pyricau** [comment]
Thank you.

**Pull request closed without merging**
